#       ------------ +  ActiCraft Mafia  + ------------   #
#                                                           #
#                            Config                         #
#                                                           #
#       --------- + ------------------------- + ---------   #

# Username
user: ""
# Password
password: ""
# Licence
licence: ""
